spring.application.name=order-service
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.data.web.pageable.serialization-mode=via_dto
spring.cache.type=redis
spring.jpa.hibernate.ddl-auto=validate

spring.profiles.active=local

spring.kafka.consumer.group-id=order-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*

kafka.topics.payment-events=payment-events
